package com.example.timewise.domain.model

import com.example.timewise.R

sealed class ImageModel(val image: Int) {
    data object Anchor : ImageModel(R.drawable.ic_label_anchor)
    data object Beach : ImageModel(R.drawable.ic_label_beach)
    data object Beer : ImageModel(R.drawable.ic_label_beer)
    data object Book : ImageModel(R.drawable.ic_label_book)
    data object Cake : ImageModel(R.drawable.ic_label_cake)
    data object Camp : ImageModel(R.drawable.ic_label_camp)
    data object Card : ImageModel(R.drawable.ic_label_card)
    data object Case : ImageModel(R.drawable.ic_label_case)
    data object Castle : ImageModel(R.drawable.ic_label_castle)
    data object Cat : ImageModel(R.drawable.ic_label_cat)
    data object Cheese : ImageModel(R.drawable.ic_label_cheese)
    data object Cinema : ImageModel(R.drawable.ic_label_cinema)
    data object Clown : ImageModel(R.drawable.ic_label_clown)
    data object Coco : ImageModel(R.drawable.ic_label_coco)
    data object Coffee : ImageModel(R.drawable.ic_label_coffee)
    data object Conch : ImageModel(R.drawable.ic_label_conch)
    data object Dessert : ImageModel(R.drawable.ic_label_dessert)
    data object Dice : ImageModel(R.drawable.ic_label_dice)
    data object Dress : ImageModel(R.drawable.ic_label_dress)
    data object Earth : ImageModel(R.drawable.ic_label_earth)
    data object Flower : ImageModel(R.drawable.ic_label_flower)
    data object Fruit : ImageModel(R.drawable.ic_label_fruit)
    data object Game : ImageModel(R.drawable.ic_label_game)
    data object Gate : ImageModel(R.drawable.ic_label_gate)
    data object Girl : ImageModel(R.drawable.ic_label_girl)
    data object Graph : ImageModel(R.drawable.ic_label_graph)
    data object IceCream : ImageModel(R.drawable.ic_label_icecream)
    data object Katana : ImageModel(R.drawable.ic_label_katana)
    data object Lemon : ImageModel(R.drawable.ic_label_lemon)
    data object Letter : ImageModel(R.drawable.ic_label_letter)
    data object Meat : ImageModel(R.drawable.ic_label_meat)
    data object Monument : ImageModel(R.drawable.ic_label_monument)
    data object Moon : ImageModel(R.drawable.ic_label_moon)
    data object Museum : ImageModel(R.drawable.ic_label_museum)
    data object Mountain : ImageModel(R.drawable.ic_label_mountain)
    data object Paint : ImageModel(R.drawable.ic_label_paint)
    data object Party : ImageModel(R.drawable.ic_label_party)
    data object Pizza : ImageModel(R.drawable.ic_label_pizza)
    data object Popcorn : ImageModel(R.drawable.ic_label_popcorn)
    data object Pumpkin : ImageModel(R.drawable.ic_label_pumpkin)
    data object Radio : ImageModel(R.drawable.ic_label_radio)
    data object School : ImageModel(R.drawable.ic_label_school)
    data object Shopping : ImageModel(R.drawable.ic_label_shopping)
    data object Skull : ImageModel(R.drawable.ic_label_skull)
    data object Soap : ImageModel(R.drawable.ic_label_soap)
    data object Store : ImageModel(R.drawable.ic_label_store)
    data object Sun : ImageModel(R.drawable.ic_label_sun)
    data object Tea : ImageModel(R.drawable.ic_label_tea)
    data object Ticket : ImageModel(R.drawable.ic_label_ticket)
    data object Time : ImageModel(R.drawable.ic_label_time)
    data object Van : ImageModel(R.drawable.ic_label_van)
    data object Wine : ImageModel(R.drawable.ic_label_wine)
    data object Winner : ImageModel(R.drawable.ic_label_winner)
    data object Xmas : ImageModel(R.drawable.ic_label_xmas)
    data object YinYang : ImageModel(R.drawable.ic_label_yinyang)
}